#!/bin/bash
#SBATCH -N 1
#SBATCH -p RM
#SBATCH -t 6:00:00
#SBATCH -J STAR-Fusion
#SBATCH -o fusion-%j.out

module load gcc/5.3.0
module load perl/5.18.4-threads
module load blast
module load samtools
module load staraligner/2.5.4b
module load star-fusion/1.3.1

STAR-Fusion --genome_lib_dir /pghbio/dbmi/Genomics_Core/rmh55/RefSeq/GRCh37_v19_CTAT_lib_Feb092018/ctat_genome_lib_build_dir \
            --examine_coding_effect \
            --FusionInspector inspect \
            --left_fq $1 \
            --right_fq $2 \
            --CPU 14 \
            --output_dir $3
